"""
SaaS Growth Analytics - Executive Metrics Module

This module computes the core SaaS performance metrics using the
subscription lifecycle dataset generated by the simulation pipeline.

The metrics represent the executive analytical layer of the project
and are designed to support growth analysis, financial monitoring,
and executive dashboards.

Metrics generated
-----------------
- Monthly Recurring Revenue (MRR)
- Active Customers
- Customer Growth Rate
- Customer Churn Rate
- Net Revenue Retention (NRR)
- ARPU (Average Revenue Per User)
- LTV (Customer Lifetime Value)

Output
------
data/processed/executive_metrics.csv
"""

import logging
import pandas as pd

import config.settings as settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------
# Metric calculations
# ---------------------------------------------------------

def calculate_mrr(df: pd.DataFrame) -> pd.DataFrame:
    """
    calculate_mrr(df)
    ----------------------

    Calculates Monthly Recurring Revenue (MRR) from a subscription history DataFrame.

    Parameters
    ----------
    df : pandas.DataFrame
        Subscription dataset with at least the following columns:
        - "year_month": datetime representing the month
        - "monthly_revenue": revenue generated by each customer for that month

    Returns
    -------
    pandas.DataFrame
        A DataFrame with columns:
        - "year_month": each month in the dataset
        - "mrr": total monthly revenue for that month, summed across all active customers

    Details
    -------
    1. Groups the input DataFrame by "year_month" and sums "monthly_revenue".
    2. Provides a time series of MRR suitable for trend analysis and growth calculations.
    3. Ignores individual customer-level details; only aggregates monthly totals.

    Example
    -------
    >>> df_mrr = calculate_mrr(subscription_history)
    >>> df_mrr.head()
    year_month   mrr
    0 2024-01-01  1024
    1 2024-02-01  1107
    2 2024-03-01  1175
    3 2024-04-01  1232
    4 2024-05-01  1301
    """

    logger.debug(
        "Starting MRR calculation | rows=%s | columns=%s",
        df.shape[0],
        df.shape[1],
    )

    try:

        mrr = (
            df.groupby("year_month")["monthly_revenue"]
            .sum()
            .reset_index(name="mrr")
        )

        logger.info(
            "MRR calculated successfully | months=%s | total_revenue=%s",
            len(mrr),
            mrr["mrr"].sum(),
        )

        logger.debug(
            "MRR head preview: %s",
            mrr.head().to_dict(orient="records"),
        )

        return mrr

    except Exception:
        logger.exception("MRR calculation failed")
        raise

def calculate_active_customers(df: pd.DataFrame) -> pd.DataFrame:
    """
    calculate_active_customers(df)
    ----------------------

    Computes the number of active customers per month from subscription history.

    Parameters
    ----------
    df : pandas.DataFrame
        Subscription dataset with at least the following columns:
        - "year_month": datetime representing the month
        - "customer_id": unique identifier for each customer
        - "active": boolean indicating if the customer is active in that month

    Returns
    -------
    pandas.DataFrame
        A DataFrame with columns:
        - "year_month": each month in the dataset
        - "active_customers": count of unique active customers in that month

    Details
    -------
    1. Filters the DataFrame to include only active customers.
    2. Groups by "year_month" and counts unique "customer_id" values.
    3. Provides a monthly time series for retention and growth analysis.

    Example
    -------
    >>> df_active = calculate_active_customers(subscription_history)
    >>> df_active.head()
    year_month  active_customers
    0 2024-01-01               200
    1 2024-02-01               210
    2 2024-03-01               225
    3 2024-04-01               230
    4 2024-05-01               242
    """
    
    logger.debug(
        "Starting active customer calculation | rows=%s | columns=%s",
        df.shape[0],
        df.shape[1],
    )

    if df.empty:
        logger.warning("Active customer calculation received empty dataframe")
        return pd.DataFrame(columns=["year_month", "active_customers"])

    try:

        active = (
            df[df["active"]]
            .groupby("year_month")["customer_id"]
            .nunique()
            .reset_index(name="active_customers")
        )

        logger.info(
            "Active customers calculated successfully | months=%s | max_active=%s",
            len(active),
            active["active_customers"].max(),
        )

        logger.debug(
            "Active customers preview: %s",
            active.head().to_dict(orient="records"),
        )

        return active

    except Exception:
        logger.exception("Active customer calculation failed")
        raise

def calculate_new_customers(df: pd.DataFrame) -> pd.DataFrame:
    """
    calculate_new_customers(df)
    ----------------------

    Calculates the number of newly acquired customers per month.

    Parameters
    ----------
    df : pandas.DataFrame
        Subscription dataset with at least the following columns:
        - "customer_id": unique identifier for each customer
        - "year_month": datetime representing the month of the record

    Returns
    -------
    pandas.DataFrame
        A DataFrame with columns:
        - "year_month": month of first appearance for customers
        - "new_customers": count of customers acquired in that month

    Details
    -------
    1. Determines the first month each customer appears in the dataset.
    2. Groups by "year_month" to count how many new customers were acquired each month.
    3. Useful for analyzing acquisition trends and feeding growth metrics.

    Example
    -------
    >>> df_new = calculate_new_customers(subscription_history)
    >>> df_new.head()
    year_month  new_customers
    0 2024-01-01            200
    1 2024-02-01             15
    2 2024-03-01             23
    3 2024-04-01             36
    4 2024-05-01             45
    """
    logger.debug(
        "Starting new customer calculation | rows=%s | columns=%s",
        df.shape[0],
        df.shape[1],
    )

    try:

        unique_customers = df["customer_id"].nunique()

        logger.debug(
            "Unique customers detected in dataset | customers=%s",
            unique_customers,
        )

        # --------------------------------------------------
        # First appearance of each customer
        # --------------------------------------------------

        first_seen = (
            df.groupby("customer_id")["year_month"]
            .min()
            .reset_index()
        )

        # --------------------------------------------------
        # Monthly acquisition counts
        # --------------------------------------------------

        new_customers = (
            first_seen.groupby("year_month")["customer_id"]
            .count()
            .reset_index(name="new_customers")
        )

        logger.info(
            "New customer acquisition calculated | months=%s | total_acquired=%s",
            len(new_customers),
            new_customers["new_customers"].sum(),
        )

        logger.debug(
            "New customer preview: %s",
            new_customers.head().to_dict(orient="records"),
        )

        return new_customers

    except Exception:
        logger.exception("New customer calculation failed")
        raise

def calculate_churned_customers(df: pd.DataFrame) -> pd.DataFrame:
    """
    calculate_churned_customers(df)
    ----------------------

    Computes the number of customers who churned each month.

    Parameters
    ----------
    df : pandas.DataFrame
        Subscription dataset with at least the following columns:
        - "year_month": datetime representing the month
        - "customer_id": unique identifier for each customer
        - "churn_flag": boolean indicating if the customer churned in that month

    Returns
    -------
    pandas.DataFrame
        A DataFrame with columns:
        - "year_month": month of churn event
        - "churned_customers": count of customers who churned in that month

    Details
    -------
    1. Filters the DataFrame to include only records where `churn_flag` is True.
    2. Groups by "year_month" and counts churned customers.
    3. Supports retention analysis, churn trend visualization, and KPIs calculation.

    Example
    -------
    >>> df_churned = calculate_churned_customers(subscription_history)
    >>> df_churned.head()
    year_month  churned_customers
    0 2024-01-01                  3
    1 2024-02-01                  4
    2 2024-03-01                  5
    3 2024-04-01                  6
    4 2024-05-01                  7
    """

    logger.debug(
        "Starting churned customer calculation | rows=%s | columns=%s",
        df.shape[0],
        df.shape[1],
    )

    if df.empty:
        logger.warning("Churn calculation received empty dataframe")
        return pd.DataFrame(columns=["year_month", "churned_customers"])

    try:

        churned = (
            df[df["churn_flag"]]
            .groupby("year_month")["customer_id"]
            .count()
            .reset_index(name="churned_customers")
        )

        total_churn = churned["churned_customers"].sum()
        peak_churn = churned["churned_customers"].max()

        logger.info(
            "Churned customers calculated | months=%s | total_churn=%s | peak_monthly_churn=%s",
            len(churned),
            total_churn,
            peak_churn,
        )

        logger.debug(
            "Churned customers preview: %s",
            churned.head().to_dict(orient="records"),
        )

        return churned

    except Exception:
        logger.exception("Churned customer calculation failed")
        raise

def calculate_expansion_revenue(df: pd.DataFrame) -> pd.DataFrame:
    """
    calculate_expansion_revenue(df)
    ----------------------

    Calculates monthly revenue generated from customer plan expansions (upgrades).

    Parameters
    ----------
    df : pandas.DataFrame
        Subscription dataset with at least the following columns:
        - "year_month": datetime representing the month
        - "monthly_revenue": revenue generated by each customer for that month
        - "expansion_flag": boolean indicating if the customer upgraded their plan that month

    Returns
    -------
    pandas.DataFrame
        A DataFrame with columns:
        - "year_month": month of expansion events
        - "expansion_revenue": total revenue from plan upgrades in that month

    Details
    -------
    1. Filters the dataset to include only records where `expansion_flag` is True.
    2. Groups by "year_month" and sums the `monthly_revenue` contributed by upgrades.
    3. Provides a monthly time series for expansion revenue analysis and KPI tracking.

    Example
    -------
    >>> df_expansion = calculate_expansion_revenue(subscription_history)
    >>> df_expansion.head()
    year_month  expansion_revenue
    0 2024-01-01                150
    1 2024-02-01                210
    2 2024-03-01                180
    3 2024-04-01                240
    4 2024-05-01                200
    """

    logger.debug(
        "Starting expansion revenue calculation | rows=%s | columns=%s",
        df.shape[0],
        df.shape[1],
    )

    if df.empty:
        logger.warning("Expansion revenue calculation received empty dataframe")
        return pd.DataFrame(columns=["year_month", "expansion_revenue"])

    try:

        expansion = (
            df[df["expansion_flag"]]
            .groupby("year_month")["monthly_revenue"]
            .sum()
            .reset_index(name="expansion_revenue")
        )

        total_expansion = expansion["expansion_revenue"].sum()
        peak_expansion = expansion["expansion_revenue"].max()

        logger.info(
            "Expansion revenue calculated | months=%s | total_expansion_revenue=%s | peak_monthly_expansion=%s",
            len(expansion),
            total_expansion,
            peak_expansion,
        )

        logger.debug(
            "Expansion revenue preview: %s",
            expansion.head().to_dict(orient="records"),
        )

        return expansion

    except Exception:
        logger.exception("Expansion revenue calculation failed")
        raise

def calculate_churn_rate(metrics_df: pd.DataFrame) -> pd.DataFrame:
    """
    calculate_churn_rate(metrics_df)
    ----------------------

    Computes the monthly customer churn rate from aggregated metrics.

    Parameters
    ----------
    metrics_df : pandas.DataFrame
        DataFrame containing monthly aggregated metrics with at least the following columns:
        - "year_month": datetime representing the month
        - "active_customers": number of active customers in that month
        - "churned_customers": number of customers who churned that month

    Returns
    -------
    pandas.DataFrame
        The input DataFrame augmented with:
        - "active_prev_month": number of active customers in the previous month
        - "churn_rate": proportion of active customers lost that month (churned / previous month active)

    Details
    -------
    1. Shifts the `active_customers` column by one month to compute previous month activity.
    2. Calculates churn rate as `churned_customers / active_prev_month`.
    3. Useful for tracking retention trends and supporting growth and strategic analysis.

    Example
    -------
    >>> df_metrics = calculate_churn_rate(metrics_df)
    >>> df_metrics.head()
    year_month  active_customers  churned_customers  active_prev_month  churn_rate
    0 2024-01-01               200                 3                NaN        NaN
    1 2024-02-01               210                 4              200.0      0.020
    2 2024-03-01               225                 5              210.0      0.024
    3 2024-04-01               230                 6              225.0      0.027
    4 2024-05-01               242                 7              230.0      0.030
    """

    logger.debug(
        "Starting churn rate calculation | rows=%s | columns=%s",
        metrics_df.shape[0],
        metrics_df.shape[1],
    )

    if metrics_df.empty:
        logger.warning("Churn rate calculation received empty dataframe")
        return metrics_df

    try:

        df = metrics_df.copy()

        # --------------------------------------------------
        # Previous month active customers
        # --------------------------------------------------

        df["active_prev_month"] = df["active_customers"].shift(1)

        # --------------------------------------------------
        # Churn rate calculation
        # --------------------------------------------------

        df["churn_rate"] = (
            df["churned_customers"] /
            df["active_prev_month"]
        )

        avg_churn = df["churn_rate"].mean(skipna=True)
        peak_churn = df["churn_rate"].max(skipna=True)

        logger.info(
            "Churn rate calculated | months=%s | avg_churn_rate=%.4f | peak_churn_rate=%.4f",
            len(df),
            avg_churn,
            peak_churn,
        )

        if peak_churn > 0.08:
            logger.warning(
                "High churn detected | peak_churn_rate=%.4f",
                peak_churn,
            )

        logger.debug(
            "Churn rate preview: %s",
            df.head().to_dict(orient="records"),
        )

        return df

    except Exception:
        logger.exception("Churn rate calculation failed")
        raise

# ---------------------------------------------------------
# Executive metrics pipeline
# ---------------------------------------------------------

def generate_executive_metrics() -> pd.DataFrame:
    """
    generate_executive_metrics()
    ----------------------

    Aggregates subscription data into a comprehensive monthly executive metrics dataset.

    Parameters
    ----------
    None

    Returns
    -------
    pandas.DataFrame
    A DataFrame containing monthly metrics for executive reporting, including:
    - "year_month": datetime of each month
    - "mrr": total monthly recurring revenue
    - "active_customers": count of active customers
    - "new_customers": count of newly acquired customers
    - "churned_customers": count of churned customers
    - "expansion_revenue": revenue from plan upgrades
    - "active_prev_month": active customers in the prior month
    - "churn_rate": proportion of active customers lost

    Details
    -------
    1. Loads subscription history from RAW_DIR/"subscriptions_monthly.csv".
    2. Computes core metrics:
    - MRR via `calculate_mrr`
    - Active customers via `calculate_active_customers`
    - New customer acquisitions via `calculate_new_customers`
    - Churned customers via `calculate_churned_customers`
    - Expansion revenue via `calculate_expansion_revenue`
    3. Merges individual metrics into a single DataFrame and fills missing values with 0.
    4. Computes derived metrics (previous month active customers and churn rate) via `calculate_churn_rate`.
    5. Saves the resulting executive metrics to PROCESSED_DIR/"executive_metrics.csv".
    6. Provides a single source of truth for dashboards and KPI computation.

    Example
    -------
    >>> df_metrics = generate_executive_metrics()
    >>> df_metrics.head()
    year_month    mrr  active_customers  new_customers  churned_customers  expansion_revenue  active_prev_month  churn_rate
    0 2024-01-01  5800               200            200                  3               150                NaN        NaN
    1 2024-02-01  6020               210             15                  4               210              200.0      0.020
    2 2024-03-01  6250               225             23                  5               180              210.0      0.024
    3 2024-04-01  6480               230             36                  6               240              225.0      0.027
    4 2024-05-01  6725               242             45                  7               200              230.0      0.030
    """

    logger.info("Starting executive metrics pipeline")

    try:

        # -----------------------------------------------------
        # Load subscription data
        # -----------------------------------------------------

        subscriptions_path = settings.RAW_DIR / "subscriptions_monthly.csv"

        logger.debug("Loading subscription data from %s", subscriptions_path)

        df = pd.read_csv(subscriptions_path)

        df["year_month"] = pd.to_datetime(df["year_month"])

        logger.info(
            "Subscription data loaded | rows=%s | columns=%s",
            df.shape[0],
            df.shape[1],
        )

        # -----------------------------------------------------
        # Individual metrics
        # -----------------------------------------------------

        logger.info("Calculating core SaaS metrics")

        mrr = calculate_mrr(df)
        active = calculate_active_customers(df)
        new_customers = calculate_new_customers(df)
        churned = calculate_churned_customers(df)
        expansion = calculate_expansion_revenue(df)

        # -----------------------------------------------------
        # Merge metrics
        # -----------------------------------------------------

        logger.debug("Merging metrics into unified dataset")

        metrics = mrr.merge(active, on="year_month", how="left")
        metrics = metrics.merge(new_customers, on="year_month", how="left")
        metrics = metrics.merge(churned, on="year_month", how="left")
        metrics = metrics.merge(expansion, on="year_month", how="left")

        metrics = metrics.fillna(0)

        logger.debug(
            "Merged metrics dataset | rows=%s | columns=%s",
            metrics.shape[0],
            metrics.shape[1],
        )

        # -----------------------------------------------------
        # Derived metrics
        # -----------------------------------------------------

        logger.info("Calculating derived metrics (churn rate)")

        metrics = calculate_churn_rate(metrics)

        # -----------------------------------------------------
        # Save results
        # -----------------------------------------------------

        settings.PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

        output_path = settings.PROCESSED_DIR / "executive_metrics.csv"

        metrics.to_csv(output_path, index=False)

        logger.info("Executive metrics saved to %s", output_path)

        # -----------------------------------------------------
        # Executive summary log
        # -----------------------------------------------------

        final_mrr = metrics["mrr"].iloc[-1]
        final_customers = metrics["active_customers"].iloc[-1]
        avg_churn = metrics["churn_rate"].mean(skipna=True)

        logger.info(
            "EXECUTIVE SUMMARY | final_mrr=%s | active_customers=%s | avg_churn=%.4f",
            final_mrr,
            final_customers,
            avg_churn,
        )

        return metrics

    except Exception:
        logger.exception("Executive metrics pipeline failed")
        raise